dataset: path  # do not change this if you want to use a self-defined dataset
# data_folder: crop_identification
data_folder: datasets/crop_identification  # root directory of your dataset
image_size: 32
batch_size: 256
num_workers: 8

model: supcon
model_args:
    encoder: resnet50
    load_pt_encoder: True  # whether load the pre-trained weights from PyTorch
    head: mlp
    feat_dim: 128
load:

loss_args:

epochs: 1000
# optimizer: sgd
# optimizer_args:
#     lr: 0.05
#     momentum: 0.9
#     weight_decay: 0.0001
optimizer: adam
optimizer_args:
#     lr: 0.001

scheduler: exp

print_freq: 10
save_freq: 100



